### ISSUE TITLE
Slow load times on initial boot of application

### ISSUE THREAD

**Issue by dehuszar** [nolanlawson/ember-pouch#112]
I've got a very basic application which uses Pouch/CouchDB, and I've got Ember Pouch successfully pulling down and loading documents on newly connecting clients.  I'm finding the initial population of data and updating of the page view to be pretty slow though.  I've seen discussion of loading db.allDocs to be painful for applications with lots of records, but I only have 25 in my app (including the design doc), and it's not going to grow by more than a few documents every several months.  Yet it takes upwards of 3-4 seconds on new clients to display any data.  My production site is being hosted on Cloudant, and my local instances don't do much better.

Here's my [adapter](https://gist.github.com/dehuszar/826ba357121e618da449).  Is there anything obvious I can be doing to speed up load times?  I've tried using only the db.allDocs, or the db.changes, but I can't really find any difference between the two in results, and the docs aren't super clear (which I'll get to in a second).

I have a static page (hard coded into the template file) that loads to begin with.  Ideally, I'd like to start downloading a few records in the background while folks are reading that, but the network doesn't try to acquire the Pouch copy until I've switched routes.  Setting my index page to retrieve data it doesn't use just to initiate the PouchDB creation seems like bad form, but I don't see any scenarios documented for bootstrapping specific content, only broad strokes examples for grabbing all docs, a single doc by id, or changed docs.

What I'm finding though is that there's not really any great descriptions of what each option means, or moreover, the meanings are muddled.  For instance, when I get allDocs, am I getting the current version of every doc, or am I getting every revision of every doc?  From what I'm seeing in my console, I'm receiving the latter (519 requests and 90MB of data).  When I request db.changes, I would presume I'm only receiving items that have changed since my last visit, and expect it to do nothing on my first visit as everything should new to me for the first visit, but that's not the case.

I think there are a few user scenarios that might be helpful to add to the docs, so that people starting out (like myself) have a foothold on what to use where.  There are [great examples](https://github.com/broerse/ember-cli-blog/blob/master/app/adapters/application.js) that I've copied from, which have been quite helpful getting set up, but there's not a ton out there on the "whys" and "what fors".  Going back to the CouchDB docs don't really help with these problems as they don't get into any more detail either.  I would be happy to contribute a PR to the documentation, but I could some guidance on the above in order to help.

Thanks!

**Comment by dehuszar** [comment]
Quick amendment.  Looks like a lot of the excessive record transfer only happens on Cloundant and not my local CouchDB server, and I'm getting a ton of `Unexpected end of input` errors from there.  O_o

**Comment by backspace** [comment]
Cloudant uses a fork of CouchDB 1.0.2, which is tragically behind the latest version. That may be one reason for performance problems, not sure.

**Comment by dehuszar** [comment]
That doesn't surprise me.  I've been working on setting up a copy using 1.6.0 on my home server that I might use instead if problems with Cloudant continue.  Is 2.0 stable enough, or containing enough benefits to make the leap?

**Comment by backspace** [comment]
I haven’t used 2.0, sorry. 1.6 works well enough for me that I haven’t bothered.

**Comment by broerse** [comment]
Do you see `Unexpected end of input` on http://bloggr.exmer.com/ ? This is also hosted on Cloudant.

**Comment by dehuszar** [comment]
Nope.  Not seeing them any more.  Just guessing, I think there may have been a failed sync.  I'm not getting those errors any more.

What I am seeing is ~19MB of _revs being downloaded.  :-/

Cloundant insists that they auto-compact all dbs.  Is there a way to prevent the downloading of all the additional revs?  I'm only grabbing 25 actual records, which consist of titles and textarea content.

https://portfolio.samuel-allen.com is where the live site now lives.  I've updated my adapter gist.  I am using @broerse's ember-cli-blog adapter almost verbatim (different loader animation process).

**Comment by nolanlawson** [comment]
@dehuszar Unfortunately that is just a fact with how PouchDB/CouchDB works. If you generate too many revisions, then those revision strings still need to be synced everywhere, which can consume a lot of bandwidth. The general solution is to not create so many revs.

E.g. if you are writing a document-editor app, then don't save a rev for every keystroke. For this reason, building Google Docs on PouchDB would not be advised; there are better solutions like Operational Transforms, e.g. as implemented by ShareJS: https://github.com/share/ShareJS

**Comment by dehuszar** [comment]
So you're saying there is no way to manually flush or limit the number of revisions generated...  It's just baked in the cake as-is?  If so, that does put a damper on things.  In that event, I would maybe suggest that a blogging application might not be the best reference example to point everyone to.

**Comment by mattmarcum** [comment]
@dehuszar have you read this? http://pouchdb.com/guides/compact-and-destroy.html  It looks like if you don't need all your revisions then you can compact the db and get rid of them.  @nolanlawson there's a line there that says that couchdb will compact too... "When you compact a database, you tell PouchDB to optimize its current storage usage. CouchDB will do the same thing"  Does this mean that when you're replicating and you compact the db via pouchdb that the remote couchdb instance will compact too?

**Comment by nolanlawson** [comment]
@mattmarcum Replications are, in a sense, automatically compacted. Please read this for an explanation: https://github.com/nolanlawson/pouchdb-full-sync
