### ISSUE TITLE
findRecord and findAll race when pouch is initializing

### ISSUE THREAD

**Issue by dweremeichik** [nolanlawson/ember-pouch#123]
I'm going to start of by stating, I'm not entirely sure if this is intentional or not. 

Let's say that I am a new user of my application. My friend gave me a link to it, and that link points to "http://myapp/items/some-item-id". Since I have never loaded up the app before, the Pouch instance in my browser needs to replicate with the application's couchdb server. In the meantime it just goes ahead and rejects the `findRecord` promise because the code races and that document has not been loaded yet (even though the link is good, and works for my friend).

Many cases won't see this as they will be using `findAll` which does not reject, it simply returns the empty set. In general this is still kind of an issue. However some users may try to overcome this by using the "semi-anti-pattern" that is used in the example application in the documentation (the adapter by @broerse) masks this (for `findAll` only). 

What I would expect should happen is that ember pouch would wait until pouch is initialized to fulfil or reject that promise and allow users to leverage ember's [loading route](https://guides.emberjs.com/v2.4.0/routing/loading-and-error-substates/).

Any thoughts on this are greatly appreciated.

**Comment by srsgores** [comment]
Interesting you're having the same problem.  Perhaps a duplicate of #121?

**Comment by dweremeichik** [comment]
I thought so too,  but then i saw you referencing index db errors. The reason that I stumbled upon this in the first place is because i have a database with about an update seq of about 1200.  20 of those documents exist,  the rest are all deleted docs. So needless to say,  my db can take over a minute to load.  

This has led me to think of interesting ways to optimize my app.  Some of them include using route specific adaptors, but since they do not load until you hit the specific route, it's not really useful.  My other options might include filtered replication. 

If index db ends up not being your problem,  then by all means this would be a duplicate.

**Comment by dweremeichik** [comment]
Deeming a duplicate of #121.
