### ISSUE TITLE
Saving and destroying relationships

### ISSUE THREAD

**Issue by dehuszar** [nolanlawson/ember-pouch#126]
I am attempting to use the EmbeddedRecordsMixin with Ember-Pouch, and I am largely having success.  I am experiencing some weirdness around saving hasMany relationships.

I am essentially trying to do the inverse of the [Removing hasMany relationships example in the README](https://github.com/nolanlawson/ember-pouch#removing).  When I create a child record, before any changes to the new record have been made, I save the child record and the parent immediately per the instructions, but ideally my UI wouldn't _require_ saving each child individually until all the child records have been modified and the parent saved (many can be open at once).

So what I'd like to do is when I'm done editing all the open children records, fire the parent's save event, and then loop through all those hasMany records I've created, save their changes and then when that's done, save the parent.

Problem is, the example indicates that I should create a statement akin to `parent.get('hasManyAttr').then(loopThroughAndSaveFunction)` (the example uses destroy, regardless...) but I'm seeing an error get thrown stating that `parent.get(...).then is not a function`.

Is that pattern dependent on something I may not be implementing correctly?  Is it an error in the docs?  Here's a [gist](https://gist.github.com/dehuszar/8dbe8138b0ef6596ef700a1b1afebb45) of my route.

I'm using Ember 2.4.2

**Comment by dehuszar** [comment]
Okay, just tried chopping out the `then` function and doing a parent.get('hasManyAttr').map(...) and that did the trick.  Is there some intent in the instructions there that need to be cleared up, or is the example in error?  I would be happy to create a PR to update the docs if it's the latter.

**Comment by dweremeichik** [comment]
@dehuszar to give you a little background information on the documentation you are referencing, I pulled it out of some working code that I had, and modified some variable names. The exact bit that it is from:
```javascript
deleteItem(item){
      let deletedDiscounts = [];
      item.get('discounts').then((discounts) => {
        discounts.map((discount) => {
          deletedDiscounts.push(discount.destroyRecord());
        });
      });
      Ember.RSVP.all(deletedDiscounts).then(() => {
        item.destroyRecord();
      });
    }
```
This gets called from a button:
```hbs
{{#each model as |item|}}
   ...
   <button type="button" {{action 'deleteItem' item}}>X</button>
   ...
{{/each}}
```
Both what is in the documentation, and your solution work  for me. The documentation was strongly based off of [Ember Fire's](https://www.firebase.com/docs/web/libraries/ember/guide.html#section-relationships) regarding relationships, check that out; it confirms what you stated in your solution.

I would like to look into it more to see why it is behaving differently for each of us.

**Comment by dehuszar** [comment]
I think it's because on my side getting the contents of the hasMany attribute doesn't return a promise, just a property, so it's not 'thennable'.

**Comment by dehuszar** [comment]
Probably a difference introduced by the embedded records mixin.  No need to go get the record as it's nested.
