### ISSUE TITLE
Test with Ember Data test suite

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/ember-pouch#13]
So right now there are automated Travis tests in relational-pouch, but I have no idea what the best practice is for an Ember/Broccoli/Ember Data plugin, so I've just punted.

Really there should be tests, though. It's kind of embarrassing that I have none.

**Comment by rsutphin** [comment]
I have not seen a generic ember-data test suite for adapters. @nolanlawson, do you remember where you heard this?

**Comment by nolanlawson** [comment]
@rsutphin I could have sworn I heard about it when I asked in the #emberjs room in IRC. But I admit it could have just been wishful thinking.

**Comment by broerse** [comment]
@nolanlawson it was @tomdale here: http://discuss.emberjs.com/t/ember-data-test-improvements/1199

**Comment by tomdale** [comment]
I don't think we ever got around to building that, but if it's something you all want to tackle that would be awesome and I'll help out however I can.

**Comment by rsutphin** [comment]
It seems like it would be really tricky to test anything meaningful in a generic way — how could a generic test harness verify that data was saved correctly or found correctly without any understanding of the underlying persistence mechanism? Seems like you'd end up implementing a second adapter — this time for the test harness. How would you verify it was correct? Maybe the second adapter could be  simpler, but I wonder how valuable it could be.

At any rate, I'll keep this in mind as I work on expanding ember-pouch's test suite and let everyone know if I any good ideas.
