### ISSUE TITLE
Using Custom Express API With PouchDB

### ISSUE THREAD

**Issue by GiovanniL19** [nolanlawson/ember-pouch#139]
Hi,

I have an existing API on a server with the port 3002. Am I able to tell pouchdb to use the API to get the data. Is this possible?

Thank you in advance!

**Comment by broerse** [comment]
This:

https://github.com/broerse/ember-cli-blog/blob/master/config/environment.js#L47


uses port 80. You can write something like: `ENV.remote_couch = '
https://martinic.cloudant.com:3002/bloggr';` for port 3002

**Comment by GiovanniL19** [comment]
Hi @broerse Thank you very much for that, however I have an issue. I keep getting not found on:

> http://localhost:3002//?_nonce=1473272426878

<img width="407" alt="screen shot 2016-09-07 at 20 05 45" src="https://cloud.githubusercontent.com/assets/10454722/18324959/f511d206-7536-11e6-8cb8-303bcca98884.png">


Also an error message saying: 

> XMLHttpRequest cannot load http://localhost:3002//?_nonce=1473272426878. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:4200' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.


I have followed the documentation provided. Sorry if I am missing something obvious, still new to all this!

**Comment by broerse** [comment]
Add CORS 
- npm install -g add-cors-to-couchdb
- add-cors-to-couchdb http://localhost:3002 -u your_username -p your_password

**Comment by broerse** [comment]
Also set

https://github.com/broerse/ember-cli-blog/blob/master/config/environment.js#L49

```
ENV.contentSecurityPolicy = {
  "connect-src": "'self' http://localhost:3002"
};
```

**Comment by backspace** [comment]
Is your API CouchDB, @GiovanniL19?

**Comment by broerse** [comment]
As @backspace noticed didn't saw the word Express in the title. You can store local data with Pouch in your browser and use an other adapter to talk to your backend. But I solved this once by syncing the data from a custom backed to a  CouchDB server on the backend with perl. (I would use node.js now) You can then use the normal CouchDB/PouchDB combination. If you only want to use the local storage function and not the Sync power also take a look at https://github.com/genkgo/ember-localforage-adapter

**Comment by GiovanniL19** [comment]
@backspace  and @broerse Thank you for your replies!

The API is connected to couchdb. My ember apps talks to the API to get the data. I will try the link you sent me and experiment a little. I may rethink how the app gets data
