### ISSUE TITLE
Soft delete functionality.

### ISSUE THREAD

**Issue by dweremeichik** [nolanlawson/ember-pouch#146]
It seems since pouch is awesome at replication, we should have the ability to do a replication safe delete. This should be opt-in; in theory all it needs to do is put `_deleted: true` on the document to be deleted.

Since delete functionality is being modified by #145 (and it makes it more useful) this should wait on that.

I can write a PR after #145 is resolved.

**Comment by jlami** [comment]
doesn't relational-pouch already handle this?

https://github.com/nolanlawson/relational-pouch/blob/master/lib/index.js#L202

**Comment by dweremeichik** [comment]
@jlami it would appear that it does, not sure why I thought it did not. Thank you!
