### ISSUE TITLE
Problem installing ember-pouch

### ISSUE THREAD

**Issue by Thewolfs** [nolanlawson/ember-pouch#157]
Hi,

I'm trying to install ember-pouch with ember-cli 2.9.1 and ember-data 2.9. Only problem I'm getting this error : 
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.

Is this an ember-pouch issue or does it come from something else ? I haven't had any issue installing other packages

Thanks for your help

**Comment by Thewolfs** [comment]
I just tryed with ember-cli 2.8.0 and I have the same issue

**Comment by dweremeichik** [comment]
@Thewolfs This is an issue with ember-pouch. 

In addition to what @Thewolfs is seeing, when you try to run ember server, you get: 

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat 'path/to/app/tmp/source_map_concat-input_base_path-kXzQ8FR4.tmp/0/bower_components/pouchdb/dist/pouchdb.js'
```
Steps to reproduce:
1. Create a new ember project - `ember new something`
2. Install ember-pouch - `ember install ember-pouch` -- this is the step where you see the issue that @Thewolfs is describing
3. Run the server - `ember serve` -- this is where you see the Broccoli error.

@broerse @Fed03 could this be related to #147?

**Comment by dweremeichik** [comment]
It appears that the [after install](https://github.com/nolanlawson/ember-pouch/blob/master/blueprints/ember-pouch/index.js#L5-L10) in the **ember-pouch** blueprint never gets run. Therefore the necessary files do not get added from bower.

@Thewolfs for a work around, add the following to the dependencies in your bower.json file: 
```json
    "pouchdb": "^5.4.5",
    "relational-pouch": "^1.4.4",
    "pouchdb-find": "^0.10.2"
```

the file should then look similar to:
```json
{
  "name": "app",
  "dependencies": {
    "ember": "~2.8.0",
    "ember-cli-shims": "0.1.1",
    "pouchdb": "^5.4.5",
    "relational-pouch": "^1.4.4",
    "pouchdb-find": "^0.10.2"
  }
}
```

Then run `bower install`.

After doing so, I was able to run `ember serve` just fine.

**Comment by Fed03** [comment]
@dweremeichik I looked into it and I think the problem is the removal of `normalizeEntityName()` method in the default blueprint. Sadly I don't know how to test if re-adding it solves the problem.

@broerse any hint?

**Comment by broerse** [comment]
@Fed03 Adding this seems to be a good thing anyway. Make the PR and I will release 4.0.2

**Comment by dweremeichik** [comment]
@Fed03 I think I have an idea for regression testing this. I will look into
it.

**Comment by broerse** [comment]
@dweremeichik @Fed03 Test 4.0.3 now

**Comment by broerse** [comment]
@Thewolfs It should be fixed in 4.0.3

**Comment by dweremeichik** [comment]
@broerse 4.0.3 seems to do the trick, thanks @Fed03! 
@Thewolfs if I am not wrong, simply doing an `ember install ember-pouch` again should update your project to the latest version.

**Comment by Fed03** [comment]
glad to help guys!

**Comment by Thewolfs** [comment]
That fixed it for me, thank you guys !
