### ISSUE TITLE
cannot find module adapters/application

### ISSUE THREAD

**Issue by MattsLab** [nolanlawson/ember-pouch#175]
I've been attempting to troubleshoot this issue but I can't seem to figure it out.

I keep getting the error:

```
Error while processing route: index Cannot find module 'inventory/adapters/application' Error: Cannot find module 'inventory/adapters/application'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename 
```

which causes the app to display nothing. The issue happens when I try loading data from the route like this:
/routes/index.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return this.get('store').findAll('inventory');
  }
});
```
./adapters/application.js
```
import { Adapter } from 'ember-pouch';
import PouchDB from 'pouchdb';
import config from './config/environment';
import Ember from 'ember';

const { assert, isEmpty } = Ember;

function createDb() {
  let localDb = config.localDb;

  assert('localDb must be set', !isEmpty(localDb));

  let db = new PouchDB(localDb);

  if (config.remoteDb) {
    let remoteDb = new PouchDB(config.remoteDb);

    db.sync(remoteDb, {
      live: true,
      retry: true
    });
  }

  return db;
}

export default Adapter.extend({
  init() {
    this._super(...arguments);
    this.set('db', createDb());
  }
});
```
If anyone could hint at what I am doing wrong that would be great.

**Comment by broerse** [comment]
Not sure but perhaps `config` is the problem. I think it should be `import config from '../config/environment';`

**Comment by MattsLab** [comment]
That was my first guess too, I changed it quite a few times to see if that was the issue. All result in the same error.

These are all the variations that I've tried.
```
import config from './config/environment';
import config from '../config/environment';
import config from 'inventory/config/environment';
```

**Comment by bendebled** [comment]
I have the same issue. How did you solve this?

**Comment by broerse** [comment]
@bendebled Perhaps compare your setup with https://github.com/broerse/ember-cli-blog to spot the difference.

**Comment by bendebled** [comment]
@broerse I actually based my code on the official doc (https://github.com/nolanlawson/ember-pouch) and on https://github.com/broerse/ember-cli-blog .

Here is my code:
app/adapters/application.js
```
import { Adapter } from 'ember-pouch';
import PouchDB from 'pouchdb';
import config from 'testa/config/environment';
import Ember from 'ember';

const { assert, isEmpty } = Ember;

function createDb() {
  let localDb = config.emberPouch.localDb;

  assert('emberPouch.localDb must be set', !isEmpty(localDb));

  let db = new PouchDB(localDb);

  return db;
}

export default Adapter.extend({
  init() {
    this._super(...arguments);
    this.set('db', createDb());
  }
});
```

config/environment.js
```
/* jshint node: true */


module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'testa',
    environment: environment,
    rootURL: null,
    locationType: 'hash',
    emberPouch: {
      dontsavehasmany: true
    },
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }
  };

  ENV.emberPouch.localDb = 'test';

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    ENV.APP.LOG_ACTIVE_GENERATION = true;
    ENV.APP.LOG_TRANSITIONS = true;
    ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...

    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {
  }



  return ENV;
};
```

app/models/todo.js
```
import Model from 'ember-pouch/model';
import DS from 'ember-data';

export default Model.extend({
  title       : DS.attr('string'),
  isCompleted : DS.attr('boolean')
});
```

app/routes/application.js
```
import Ember from 'ember';
export default Ember.Route.extend({
  model() {
    return this.store.findAll('todo');
  }
});
```

The error appears if the line `return this.store.findAll('todo');` is in `app/routes/application.js`. If I comment that line, then there are no errors.

**Comment by broerse** [comment]
What happens when you write `import config from '../config/environment';` ??

**Comment by bendebled** [comment]
@broerse I've already tried, and I retried (even with ../../ and ./ (you never know...)) And I get the same errror.

**Comment by broerse** [comment]
@bendebled I cloned the `ember-cli-todos` and add `ember-pouch`. Don't get your error and it works fine.

https://github.com/broerse/ember-cli-todos

**Comment by Tyris** [comment]
I'm getting this same issue... after quite a bit of digging it looks like this error is the cause:

> "Could not find module `ember-getowner-polyfill` imported from `ember-pouch/adapters/pouch`"

It does seem to be listed in the ember-pouch dependencies, so I'm not sure why npm isn't installing it... but installing it using `ember install ember-getowner-polyfill` seems to work (So far).
