### ISSUE TITLE
runaway revs on the todo mvc app

### ISSUE THREAD

**Issue by jchris** [nolanlawson/ember-pouch#18]
So I added the rev property to the todo model, and the rev keeps incrementing as fast as it can. It's up to the 1200s now.

![screen shot 2014-12-04 at 4 34 52 am](https://cloud.githubusercontent.com/assets/253/5298330/3d4453b4-7b6f-11e4-9245-3daef2fe73b6.png)

**Comment by rsutphin** [comment]
It sounds like this issue turned out not to be a problem in ember-pouch. Let me know if not and we can re-open it.
