### ISSUE TITLE
ember-getowner-pollyfill issue

### ISSUE THREAD

**Issue by maxwondercorn** [nolanlawson/ember-pouch#181]
I've been trying to use ember-pouch with the ember-electron add-on and kept running into issues.  I built a simple ember only app to eliminate any potential electron conflicts.  While some of my original errors have gone away, I have new ones. Following the readme, I get errors.

The first is  

> TypeError: Cannot set property 'localDb' of undefined

when you add

`ENV.emberPouch.localDb = 'test';`

I hardcoded the db name in the adapter to get around this issue.  This issue also occurred with the ember-electron add-on.  

The second issues is not finding the ember-getowner-pollyfill module. I manually installed the module, so it's available.  I also downgraded to the specific version called out ember-pouch's package.json.  Searching I see different issues with the polyfill module but none that would address this issue. 

Edited:  Ember 2.12.1 and Data 2.12.2

**Comment by broerse** [comment]
@maxwondercorn The polyfill should be fixed in v4.2.5

**Comment by maxwondercorn** [comment]
Polyfill error is now fixed. thanks

**Comment by broerse** [comment]
Thanks for the feedback,
