### ISSUE TITLE
ember-cli addon

### ISSUE THREAD

**Issue by tchak** [nolanlawson/ember-pouch#20]
Hi,
I done some initial work in making the project in to a proper ember-cli addon. With some refactoring on the way (could not help myself :)).

https://github.com/tchak/ember-pouch/commit/d573a41226a81aa5148ec04d330193a33c2aebbf

Would you be interested in a PR ? Or do you prefer to keep your less opinionated project as is?
We can probably find some middle-ground. Like I can extract some changes in your project and then release `ember-cli-pouch` wrapper relying on bower build from `ember-pouch`. Let me know how you fill about it.

**Comment by osxi** [comment]
@tchak: Any word on this?

**Comment by gregorybleiker** [comment]
Definitely seems to be the way to go... any news?

**Comment by nolanlawson** [comment]
Okay, so we are much closer to getting CLI support. @fsmanuel has done the lion's share of the work in #55, and I have a couple pull requests open (#58 and #59) which should clean up the last little bits.

The big question for me, before I publish, is: this is a breaking change, right? Seems that the `dist/` directory is different from before, so people directly using `bower`/`npm` will have to change their workflow and use `ember-cli` instead (probably not a hard sell for most Ember users).

Another question: are we supporting enough versions of ember-data? Looks like the new Travis tests are passing in Ember beta/release/canary, so I'm hoping that's enough. :)

I'm going to wait for some feedback before I publish, but so far #55 is looking pretty good!

**Comment by rsutphin** [comment]
The ember-cli addon version is 2.x.
