### ISSUE TITLE
Any way to track requests in progress? For acceptance tests

### ISSUE THREAD

**Issue by backspace** [nolanlawson/ember-pouch#27]
I was having intermittent failures in my acceptance tests that I was able to [fix](https://github.com/backspace/awdb/commit/8295365a76452f2e0f127bd71225fcfe0ff9913b) using [this technique](https://stackoverflow.com/a/27085279/760389) of setting a promise on the controller that the test waits for the resolution of. It seems unfortunate to me to add test-specific code to the application, so I’ve been looking into how the `andThen` acceptance test helper determines when asynchronous operations are complete so it can check the expectations.

I think the key code is [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L175-L200). This line would be helpful if the application were backed by a REST/AJAX database:

```javascript
// 2. If there are pending Ajax requests, keep polling
if (Test.pendingAjaxRequests) { return; }
```

[Elsewhere](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/setup_for_testing.js#L48-L49), they register to listen for AJAX events and operate on the counter that way:

```javascript
jQuery(document).on('ajaxSend', incrementAjaxPendingRequests);
jQuery(document).on('ajaxComplete', decrementAjaxPendingRequests);
```

So, my question, is there a way I can detect an ongoing PouchDB operation and delay the progression of the test until the operation is complete? I looked at [`PouchDB.on`](http://pouchdb.com/api.html#events), but it’s apparently only for `created` and `destroyed` events.

Maybe there’s a way to include this kind of functionality in `ember-pouch` to facilitate acceptance tests. Like setting a flag before a call to `this.db.rel.find` and the like, and unsetting it when the operation completes. Then I could override [`setupForTesting'](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/setup_for_testing.js#L33) and pretend that a PouchDB operation is an AJAX operation, for the purposes of testing.

Ideally, `ember-testing` would have a facility where ongoing asynchronous operations can be registered to delay test progression, but I’m not optimistic on that happening.

This may not be something you want `ember-pouch` to be concerned with, though, understandably.

**Comment by gabrielgrant** [comment]
I've been using a [custom test waiter](https://github.com/gabrielgrant/ember-cli-test-model-waiter) that is similar to your wait-for-model code, @rsutphin , but just automatically waits for all models to settle (so there's no adapter-specific code needed in your tests).

You can install it with `ember install ember-cli-test-model-waiter` (note, though, that the model-finding code only works with Ember 2.0 + at the moment)

**Comment by rsutphin** [comment]
Neat. Thanks for sharing that.

**Comment by gabrielgrant** [comment]
[Inspired by your code](https://github.com/gabrielgrant/ember-cli-test-model-waiter/blob/master/addon/instance-initializers/test-model-waiter.js#L25), @rsutphin, so thank _you_ :)

**Comment by nolanlawson** [comment]
Closing unless you still think this is an issue. Thanks for the discussion! :)
