### ISSUE TITLE
Automatically handle adding rev property?

### ISSUE THREAD

**Issue by devinrhode2** [nolanlawson/ember-pouch#29]
I noticed that @taras's[`ember-pouchDB`](https://github.com/TARAS/ember-pouchDB) library doesn't require you to add `rev` properties to each model.

This is the code from his project that handles that: [/lib/ember-pouchdb/storage.js](https://github.com/taras/ember-pouchdb/blob/master/lib/ember-pouchdb/storage.js).
<sub>(storage.js imports Model from [/lib/ember-pouchdb/model.js](https://github.com/taras/ember-pouchdb/blob/master/lib/ember-pouchdb/model.js) which is the only other file referencing the `rev` property)</sub>

I would imagine there's some good way to automatically handle adding the same string field to every model so a user doesn't have to do this. <sub>(and if there isn't a good way that maybe there should be some api added to ember or pouchdb)</sub>

**Comment by devinrhode2** [comment]
Ah, no I realized probably the best api would be to use a Ember-Pouch's own model methods, (`DS.Pouch.Model.extend({`) so in case there are any changes the library want's to make with how models are handled it can make those changes without the user having to do anything. I think in the virtue of jQuery and Ember DS.Model should not be touched, but I think adding unique properties to DS is fine and this communicates that the model is still an Ember-data model (imo)

**Comment by iUtvikler** [comment]
This is fixed in [PR#32](https://github.com/nolanlawson/ember-pouch/pull/32). It's handled by the serializer.

**Comment by rsutphin** [comment]
ember-pouch 2.0 provides a [`Model`](https://github.com/nolanlawson/ember-pouch/blob/v2.0.0/addon/model.js) base class which does this.
