### ISSUE TITLE
Question about using database per instance

### ISSUE THREAD

**Issue by igorrKurr** [nolanlawson/ember-pouch#33]
Hi!

In my application I want to have separate database for each Ember model called `Project`. The project is something like a container for model `Todo`.

And one of my usecases is just to show all todos for project. But I have separate db for each of them.
So how can I toggle between my dbs "on the fly"?

My idea is to to reopen `Todo` adapter and redefine db like this:

```javascript
if (!Ember.isEmpty(project.get('projectDbName'))) {
  var dbName = project.get('projectDbName');
  var db = new PouchDB(dbName);
  var remote = new PouchDB('http://127.0.0.1:5984/%@'.fmt(dbName));

  var doSync = function() {
    db.sync(remote, {
      live: true
    }).on('error', function() {
      setTimeout(doSync, 1000);
    });
  }
  doSync();
  TodoAdapter.reopen({
    db: db
  });
}
```

But this seems to be not working.

**Comment by TameBadger** [comment]
Hi @igorrKurr, just wondering what you ended up doing ? In a similar scenario, I wouldn't have to switch between db's on the fly to the degree that you have to, but would prefer doing a filtered replication or creating views indexed by project id.

**Comment by igorrKurr** [comment]
Hi! 
It was long time ago, but as far as i remember I decided to don't use that approach after I read all comments on this issue and I moved back to usual scenario of using pouchdb with couchdb - one pouchdb instance that syncs one couchdb database.
