### ISSUE TITLE
How to include in an ember-tools project

### ISSUE THREAD

**Issue by fibble** [nolanlawson/ember-pouch#35]
Hi,

Im going to implement findQuery() in ember-pouch but the project I need to use it in is being built using ember-tools (which is based on commonJS) and the build process is complaining of missing include files which i cant find in the ember-pouch or relational-pouch repos.

e.g. Error: Cannot find module './reject'

Could anyone suggest the best way to include ember-pouch, relational-pouch and pouchdb in an ember-tools project?

cheers

**Comment by stefanpenner** [comment]
Just a heads-up `ember-tools` isn't really supported or maintained anymore. We recommend `ember-cli` which is actively maintained, and will become part of ember 2.0 official offering.

That being said, the CJS output of this project should work correctly for your usecase.

**Comment by fibble** [comment]
Hey,

Yeah we have an outstanding task to migrate to ember-cli.

Ive used the cjs files but hit some problems with missing require()' files..

**Comment by nolanlawson** [comment]
Sounds interesting, although I think `findQuery` should probably be implemented over in `relational-pouch` first.

I've actually been meaning to ask some Ember folks about what they would recommend for that. CouchDB map/reduce doesn't fit very neatly into most `findQuery` implementations I've seen out there, so I'm not really sure how it should be written.

**Comment by nolanlawson** [comment]
ooh actually this would be a good time to start tying this into the CouchDB 2.0 query language plugin I've been working on: https://github.com/nolanlawson/pouchdb-indexes

**Comment by nolanlawson** [comment]
related to https://github.com/nolanlawson/relational-pouch/issues/3

**Comment by rsutphin** [comment]
Since we're not supporting the CJS version anymore, I think this issue is moot. (Querying is being tracked in #7.) Please let me know if I'm mistaken and there's something else I can help with.
