### ISSUE TITLE
Make changes listener optional

### ISSUE THREAD

**Issue by ssured** [nolanlawson/ember-pouch#39]
Right now https://github.com/nolanlawson/ember-pouch/blob/master/lib/pouchdb-adapter.js#L10-L24 always runs. I have a different implementation of the change feed and have to modify the source. I'd like to add a flag/option somewhere to specify if this code should run or not.

The code I use for sync following does not reload all records, but tries to discover what happened and to only update what is necessary:

```coffeescript
      db.on 'change', (change) =>
        return if change.id.match /^_design\//
        db.setSchema [] unless db.rel # make sure relational pouch is triggered
        {type, id} = db.rel.parseDocID change.id
        console.log 'got change', type, id, change
        record = @get('store').getById type, id # ask store for the record without loading it
        if change.deleted          
          record.unloadRecord() if record?
        else
          #test if the record is known in the store
          if record?
            if record.get('isEmpty') || record.get('isLoading') || record.get('isSaving') || record.get('isReloading')
              record.one 'didLoad', -> Ember.run.next ->
                return if record.get 'isDestroyed'
                try
                  console.log 'reload', record, 'after waiting for being loaded'
                  record.reload()
                catch e
            else
              if change.changes[0].rev == record.get('rev')
                return console.log 'no reload needed because we already have the correct rev (we triggered the change)', record
              console.log 'will reload', type, id, 'because of server change'
              record.reload()
          else
            #record is not known, but may be a match for a findAll
            model = @get('store').modelFor type
            typeMap = @get('store').typeMapFor model
            return unless typeMap.findAllCache? # private property of Ember Data
            console.log 'will load record', id, 'as a findAll on', type, 'exists'
            return Ember.run.later =>
              @get('store').find type, id
            , 500
```

Sorry for the coffeescript, I hope it inspires others

**Comment by rsutphin** [comment]
FWIW, #43 changes the default change handler to have some of the behavior you have in your example. (Skipping _design, not running before relational-pouch is initialized, not loading records that aren't already in the store.)

It's too bad you can't do the is-there-a-find-all check using a public API in ember-data.

**Comment by rsutphin** [comment]
In the current version of the adapter you can change the behavior of the automatic change listener by overriding the [`onChange`](https://github.com/nolanlawson/ember-pouch/blob/v2.0.0/addon/adapters/pouch.js#L30) method.
