### ISSUE TITLE
ArrayController SortableMixin not working on store?

### ISSUE THREAD

**Issue by acao** [nolanlawson/ember-pouch#49]
I may have this poorly configured, but here is an idea:

Using pouch-find I create an index (because it wasn't working without an index, thought this may help)
```js
db.createIndex({
  index: {
    fields: ['startDate', 'endDate']
  }
}).then(function (result) {
  console.log(result)
}).catch(function (err) {
 console.log(error)
});
```

Then in the controller for the route:

```js
export default Ember.ArrayController.extend({
  sortProperties: 'startDate',
  filterBy: 'startDate'
});
```

What am I missing here?

Being able to use the ArrayController seems like it will be a nice alternative to trying to get pouch-find working with relational pouch, but it just doesn't seem to be working properly.  All I need is your normal upcoming events list - startDate $gte this morning, sorted by startDate ascending, only showing items with a date (for now). If I wanted to be really messy I could use async sortBy and filterBy to mess with the controller model property.

How would you resolve this issue with ember data?

**Comment by nolanlawson** [comment]
I'm guessing this is because `query()` is not implemented yet? https://github.com/nolanlawson/ember-pouch/issues/7

BTW it ought to be fairly easy to implement, now that `pouchdb-find` exists.

**Comment by rsutphin** [comment]
`SortableMixin` is independent of ember-data — it works on the objects that are provided as the model for the controller, regardless of where they came from. Just using `sortProperties` ought to work.

Two possibilities:

1) I've always seen `sortProperties` as an array, never a single value. Have you tried `['startDate']`?
2) How are you rendering the results? `SortableMixin` doesn't sort the array in place; it makes a copy which it keeps sorted as the original array has items added/removed. Make sure you're using `arrangedContent` or the controller itself in your template, not `content` or `model`.

**Comment by acao** [comment]
@nolanlawson yes this would make using pouchdb-find a lot easier with ember data! I've been following #7, maybe I should get ambitious and take a stab at it!

@rsutphin indeed! 

I originally tried sortBy with array (sortProperties is now just a placeholder for sortBy), then sortProperties with array. docs say a string or array is acceptable

2) Ah!  Looks like I need to do more homework before gallavanting down SortableMixin lane. This is likely the problem.

**Comment by rsutphin** [comment]
@acao, I'm going to close this. Please feel free to leave a comment or open another issue if you find a problem with ember-pouch in your investigations.
