### ISSUE TITLE
Can't set up ember-pouch

### ISSUE THREAD

**Issue by scandinave** [nolanlawson/ember-pouch#52]
HI,
I'm new with Ember and so with ember-pouch. I try to set up the adapter but i'm facing some problems. I use Ember 1.11.3, Ember data 1.16.1 with ember-pouch 1.2.5

This is my app/adapter/application.js
```javascript
import config from '../config/environment';

var remote = new PouchDB(config.remote_couch);
var db = new PouchDB(config.local_couch);
PouchDB.debug.enable('*');
db.sync(remote, {
   live: true,   // do a live, ongoing sync
   retry: true   // retry if the conection is lost
});

export default EmberPouch.Adapter.extend({
  db: db
});
```

And this is errors: 
```Batchfile
adapters/application.js: line 3, col 18, 'PouchDB' is not defined.
adapters/application.js: line 4, col 14, 'PouchDB' is not defined.
adapters/application.js: line 5, col 1, 'PouchDB' is not defined.
adapters/application.js: line 11, col 16, 'EmberPouch' is not defined.
```
I've tried to add this line on top of application.js
```javascript
import PouchDB from 'ember-pouch';
import EmberPouch from 'ember-pouch';
```
but i've got this error : 
```Batchfile
Could not find module `ember-pouch` imported from `myapp/adapters/application`" "requireFrom@http://localhost:4200/assets/vendor.js:119:1
```

One idea what i did wrong?

**Comment by nolanlawson** [comment]
Hmm, did you try to run the sample app? Maybe you forgot to npm install or bower indtall... https://github.com/broerse/ember-cli-blog

**Comment by scandinave** [comment]
Yes the demo work like a charm. And my app work a little better. I think i've forgotten to install
```
npm install -g add-cors-to-couchdb
```
I still have JSHint that throw this error : 
```
adapters/application.js: line 3, col 18, 'PouchDB' is not defined.
adapters/application.js: line 4, col 14, 'PouchDB' is not defined.
adapters/application.js: line 5, col 1, 'PouchDB' is not defined.
adapters/application.js: line 11, col 16, 'EmberPouch' is not defined.
```
But now i have pouchdb  that log in console. 
it's strange no?

**Comment by rsutphin** [comment]
It looks like you're using ember-cli. How did you import ember-pouch in your Brocfile.js? I use globals, so I have:

```javascript
# Brocfile.js

app.import('bower_components/pouchdb/dist/pouchdb.js');
app.import('bower_components/relational-pouch/dist/pouchdb.relational-pouch.js');
app.import('bower_components/ember-pouch/dist/globals/main.js');
```

Then in the adapter, instead of `import`s for PouchDB, I have `/*globals EmberPouch, PouchDB */`.

**Comment by scandinave** [comment]
Yeah, this is the solution. You save my day. Thank you both. Maybe this can be add to the README for those  that use Ember-cli?

**Comment by nolanlawson** [comment]
Yes! Could you please modify the README @scandinave so that it includes the solution? Would be very helpful for the (vast majority of) Ember users who are using `ember-cli`. :smiley:

**Comment by scandinave** [comment]
Yeah. I will modify it tomorrow. I dont have tome this night. :)
