### ISSUE TITLE
Serialize to different data format?

### ISSUE THREAD

**Issue by appleton** [nolanlawson/ember-pouch#53]
I am working with an existing CouchDB dataset where records are structured like this:

```json
{
  "_id": "...",
  "_rev": "...",
  "my_attr": "value",
  "my_other_attr": "value"
}
```

Ember pouch seems to want my data in this format:

```json
{
  "_id": "...",
  "_rev": "...",
  "data": {
    "my_attr": "value",
    "my_other_attr": "value"    
  }
}
```

Whilst I like this in principle it's not practical for me to migrate my CouchDB data as there are other clients which depend on the existing format. My question is, do you know of a good way which I can serialize and deserialize data between the two formats?

I'm wondering if there's somewhere I can get inbetween the replication from PouchDB to CouchDB and transform the data? Any help would be greatly appreciated!

**Comment by appleton** [comment]
As is always the way, I've figured it out but only after asking the question. Thanks for writing [transform-pouch](https://github.com/nolanlawson/transform-pouch) @nolanlawson! :heart:

**Comment by nolanlawson** [comment]
Haha, glad it worked out! :)

**Comment by scytalezero** [comment]
Thanks @appleton , your post really helped me out with my existing CouchDB database!
