### ISSUE TITLE
docs / query about deleted item tombstones and which system introduces them

### ISSUE THREAD

**Issue by nruth** [nolanlawson/ember-pouch#61]
I'm new to couch and pouch, but this addon [was suggested as a way to persist data across page reloads](http://discuss.emberjs.com/t/robust-client-state-how-where-to-store/8107/7), and so far it seems like a really great solution.

I've noticed tombstones are getting left behind when I use destroyRecord() in ember, e.g. 
`{_deleted: true, _doc_id_rev: '...'}`. I think I know the theory behind these, and would like to know if there's a way to garbage collect them, or disable them, in an app-specific / model-specific fashion.

Also which system introduces the use of tombstones, so I can figure out which docs to read about their semantics: couchdb, pouchdb, relational pouch? I think it'd be an interesting thing to add to the readme for people who need to explore the system's behaviour.

**Comment by nruth** [comment]
The behaviour is explained here, 
http://pouchdb.com/guides/updating-deleting.html
http://pouchdb.com/guides/compact-and-destroy.html

I guess having the tombstones lying around is just a feature to live with, and my usage is abnormal.

**Comment by rsutphin** [comment]
As you've found in the docs, the _deleted records are necessary for syncing to work. But they shouldn't interfere with local use of the database — they shouldn't be returned from queries, e.g., unless you ask for them. What are you seeing that doesn't work the way you expect?

**Comment by nruth** [comment]
Nothing, just concerned about storage limits.

**Comment by nruth** [comment]
I think it probably isn't a real concern. There's always destroy db in the worst-case. I just wondered if there was a way to prune tombstones in this system, as it's often commented on in academia for systems using them, but it appears not?

**Comment by rsutphin** [comment]
In CouchDB, there's the purge operation, but it looks like PouchDB doesn't support that yet (pouchdb/pouchdb#3775).

**Comment by nruth** [comment]
OK, thanks for the information!
