### ISSUE TITLE
Usage of `typeKey` has been deprecated warning with Ember-Data 1.0.0-beta.18

### ISSUE THREAD

**Issue by OleRoel** [nolanlawson/ember-pouch#62]
I get a lot of 'DEPRECATION: Usage of `typeKey` has been deprecated and will be removed in Ember Data 1.0. It has been replaced by `modelName` on the model class.' messages in my console lately.

The warning has been introduced with 1.0.0-beta.18:

https://github.com/emberjs/data/blob/master/CHANGELOG.md#release-100-beta18-may-18-2015

**Comment by OleRoel** [comment]
Not sure if the fix is really that simple, but a quick find/replace of `typeKey` with `modelName` in addon/adapters/pouch.js makes the deprecation warning go away. Time for a PR? And what's about backward compatibility?

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/ember-pouch/pull/64
