### ISSUE TITLE
Relationship in model generates "Cannot read property ‘has’ of undefined' exception" with Ember Data 1.13.0

### ISSUE THREAD

**Issue by OleRoel** [nolanlawson/ember-pouch#66]
When I use a relationship in my model like:

```javascript
import DS from "ember-data";
import { Model } from 'ember-pouch';

var Modelname = Model.extend({
	name: DS.attr('string', {defaultValue: ""}),
	pages: DS.hasMany('page', {async: true, serialize: true})
});

export default Modelname;
```

The code is borrowed from @broerse from [where the discussion started](http://discuss.emberjs.com/t/cannot-read-property-has-of-undefined/8187). The problem seems to be introduced with verson 19.1 of ember-data as brianmbutler states in the original discussion.

The same exception pops up with `DS.belongsTo`.

With help of the Chrome debugger I was able to find the culprit in the init method.

```javascript
...
if (!Ember.get(type, 'attributes').has('rev')) {
...
```

https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L82

expects type to be a model object but gets a string when a relationship is defined inside your model.

**Comment by OleRoel** [comment]
The `store.findAll` seems to trigger the exception. This ends up in the corresponding adapter method

https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L191

where `this._init(type)`gets called with a string.

**Comment by rsutphin** [comment]
This is the problem that's causing the tests for #65 to fail, also. It's a change between 1.0-beta18 and 1.0-beta19. I think it's unintended because of the documentation you cite, @OleRoel. I've been continuing to use beta18 until I have a chance to work up a reproducible case for ED.

**Comment by OleRoel** [comment]
Just reported what appears to me an ember-data bug [here](https://github.com/emberjs/data/issues/3373).

**Comment by OleRoel** [comment]
Just created an PR for this issue.

@rsutphin Can you give me a little guidance of how to run the tests? The integration-tests are failing here with 'Can't find variable: PouchDB' errors when I simply run `ember test`on the command line.

**Comment by rsutphin** [comment]
@OleRoel, did you run `npm install` and `bower install` before you tried to run the tests?

**Comment by OleRoel** [comment]
@rsutphin Yes, I did. I'll try to find out what I am doing wrong tonight.

**Comment by rsutphin** [comment]
@OleRoel, I just tried again and I found that `ember test` didn't work for me either. However, `ember try default test` does work. `ember try` is how travis is running the tests, too, and how I was running them when I was writing them. Not sure why `ember test` alone does not work — must be something about the ember-try configuration which the tests are relying on somehow.

**Comment by OleRoel** [comment]
Got still the same problem with the tests:
```shell
not ok 10 PhantomJS 1.9 - adapter:pouch [integration]: can find all
    ---
        actual: >
            null
        message: >
            beforeEach failed on can find all: Can't find variable: PouchDB
        Log: >
    ...
```

But we might discuss this somewhere else. On the other hand: the PR tests are failing with simillar looking errors.

**Comment by rsutphin** [comment]
@OleRoel, I commented about the PR tests over on #67. I just realized what your problem is — you need PhantomJS 2.0. 1.9 won't work (PouchDB doesn't work with 1.9).

**Comment by OleRoel** [comment]
@rsutphin 
Thank you, but still get problems with PhantomJS 2.0

```shell
not ok 10 PhantomJS 2.0 - adapter:pouch [integration]: can find all
    ---
        actual: >
            false
        expected: >
            true
        message: >
            error in test:Error: Could not find module `ember-pouch/index` imported from `dummy/adapters/application`
        Log: >
    ...
´´´

**Comment by rsutphin** [comment]
That's the same as the ember-beta CI failure on #67. What versions of ember and ember-data are you testing with?

**Comment by OleRoel** [comment]
I guess that I am using the unchanged bower.json from the ember-pouch repo. Propably a naive approach, since ember and ember-data are quite outdated.

```javascript
...
  "dependencies": {
    "ember": "1.12.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "~1.0.0-beta.12",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1",
    "pouchdb": "^3.5.0",
    "relational-pouch": "^1.3.2"
  }
...
```

**Comment by rsutphin** [comment]
If you're running with ember-try, the bower.json is just the starting point. ember-try builds a new bower.json based on the ember-try configuration you're using. It should list the actual versions in use when it runs the tests.

Any any rate, I'm pretty sure with that error you're using ember 2.0-beta. If so, note that it doesn't seem to work with [ember-pouch right now (or at least the tests)](https://travis-ci.org/nolanlawson/ember-pouch/jobs/67412461), so use a different configuration.

**Comment by brianmbutler** [comment]
Ok, some progress, try this:

1.  Update ember to canary.
2.  incorporate Oleroel's PR for issue 66 that's failing tests.
3.  Update ember-data to 1.13.2.   It won't build due to ArrayPolyfill being removed from ED.
4.  See https://github.com/emberjs/data/commit/5f1dd3cb3da78955df6267133abfb4e09f42b367   Steph removed as part of IE8 support removal.
5.  To incorporate that, update your ember-data to canary.
6.  A new app will build with no errors!

However - if you add a basic:
```javascript
model() {
   return this.store.find('foo');
  }
```

You will get a new error:

Line 117 in pouch.js "Uncaught TypeError: Cannot read property 'getRecordTypeName' of undefined"
```type: this.getRecordTypeName(relModel),```

The block is

```javascript
 var relDef = {},
            relModel = typeof rel.type === 'string' ? store.modelFor(rel.type) : rel.type;
        relDef[rel.kind] = {
          type: this.getRecordTypeName(relModel),
          options: rel.options
        };
```

**Comment by OleRoel** [comment]
@brianmbutler 
I've added a check for the existance of the related model (https://github.com/nolanlawson/ember-pouch/commit/0f8ac04ff317ce08265ab4f37749c3780a14a731).

@rsutphin 
My bad, I ran `ember test` instead of `ember try default test`, now things are looking better (fail 0). However, I've to admit that we have no tests for related models.

**Comment by broerse** [comment]
Thanks all. Will try it as soon as possible.
