### ISSUE TITLE
Adapter#find has been deprecated and renamed to `findRecord`.

### ISSUE THREAD

**Issue by OleRoel** [nolanlawson/ember-pouch#72]
This has been introduced with ED 1.13, the PR can be found here: https://github.com/emberjs/data/pull/3306. We should keep a proxy ` find` method for backwards compatibilty which just forwards to  `findRecord`. ~~It's too late here for me to set up a PR, anyone who likes to jump in?~~

**Comment by OleRoel** [comment]
There are more deprecation warnings with ember-pouch:
  * Using store.getById() has been deprecated. Use store.peekRecord to get a record by a given type and ID without triggering a fetch
  * DS.Model#isDirty has been deprecated please use hasDirtyAttributes instead
  * You tried to look up 'store:main', but this has been deprecated in favor of 'service:store'

Not sure how to handle this one (just ignore it?):
  * The default behavior of shouldReloadAll will change in Ember Data 2.0 to always return false when there is at least one "agent" record in the store. If you would like to preserve the current behavior please override shouldReloadAll in you adapter:application and return true.

**Comment by OleRoel** [comment]
A table with ED store API changes can be found here: http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html

Ember beta.19| Ember 1.13
------------ | -------------
`store.getById(type, id)` | `store.peekRecord(type, id)`
`store.all(type)`| `store.peekAll(type)`
`store.find(type, id)`| `store.findRecord(type, id, options)`
`store.find(type)`  | `store.findAll(type, options)`
N/A | `store.queryRecord(type, query)`
`store.find(type, { query })` | `store.query(type, query)`
`store.fetch(type, id)` | `store.findRecord(type, id, {reload: true})`

**Comment by rsutphin** [comment]
> There are more deprecation warnings with ember-pouch:

I opened a new issue for these — #78.

> Not sure how to handle this one (just ignore it?):

I think this is one that needs to be decided on for each application.

I'm going to close this issue now since the main topic was fixed by #75.
