### ISSUE TITLE
Adding new npm maintainers

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/ember-pouch#77]
I've been slow to respond to issues recently, mostly due to going on vacation for the past few weeks.

I'd hate to see progress stalled on this project due to my own lack of free time, so if the other maintainers could please post their npm usernames here, I'd be happy to add them as npm authors so that they can publish. :)

**Comment by rsutphin** [comment]
I'm rsutphin there, too.

**Comment by rsutphin** [comment]
Thanks for the trust, btw.

**Comment by broerse** [comment]
:+1:

**Comment by OleRoel** [comment]
:+1:

**Comment by nolanlawson** [comment]
@rsutphin You are an owner in npm now. Great power, great responsibility, yada yada. :wink: 

My only advice is to use your best judgment and look for +1s from the community before merging something. I'm happy to advise on PouchDB-related issues, but I admit that I haven't used Ember in a long time, and so I'm really out-of-date with changes in Ember Data. At work, we use React and YUI, and in my personal projects I'm mostly using Angular or raw DOM, so that's another reason I'm not able to keep up.

I'm really touched and honestly kinda blown away by how the community really picked up this plugin and ran with it. I think it's a testament to the Ember community; I've never seen any other group so eager to roll up their sleeves and make one of my libraries better. At some point, if I really drop off the face of the Earth, I'd be happy to create a Github organization or something so that it's no longer under my name, but I'll let you all be the judge of when it's time to do that. :)

Thanks so much, and awesome job to everybody involved.

**Comment by OleRoel** [comment]
@nolanlawson Sad to hear that you take a step away from this repo, but after I've stumbled upon your name in blogs and GitHub related projects so often lately I was thinking this guy has either no free time or owns a second parallel universe where he can load balance some tasks. Thank you for the Ember plugin, it is a key component of a project I am working on.

@rsutphin Good to hear that you take responsibility for npm. I am really confident that you are the right guy for this.

**Comment by nolanlawson** [comment]
@OleRoel That parallel universe is called my personal life, which I basically haven't had for the past year or so. ;) Thanks for understanding!

**Comment by rsutphin** [comment]
I've published 2.0.2 with @OleRoel's fix for #72. Thanks again for your trust, @nolanlawson. I know we all appreciate the work you do on PouchDB itself and your other contributions (I've learned a lot from your PouchDB blog posts).

**Comment by nolanlawson** [comment]
Thanks, and I really appreciate you swooping in to help out.  :) Many people don't realize that open-source software is a full-time job (in addition to our regular jobs!), so it's *so helpful* when I don't have to spread myself so thin. :)

**Comment by nolanlawson** [comment]
Leaving this issue open in case anybody else wants to be added as a npm owner. @broerse I realized I didn't even add you as a Github collaborator (my bad, sorry!), but you are one now.

**Comment by broerse** [comment]
@nolanlawson Thanks. I hope I can help out.
