### ISSUE TITLE
Check the rev to avoid unnecessary reloads in change watcher

### ISSUE THREAD

**Issue by rsutphin** [nolanlawson/ember-pouch#81]
The change watcher calls `reload` when a change is encountered for a record that is in ember-data's store cache. However, the change notifier in PouchDB notifies for all changes, including ones that originated in the ember app. Compare the rev of the change to the rev the store knows about and avoid reloading for those changes.

Originally suggested by @broerse in comments on #50.

**Comment by broerse** [comment]
My changes seem to work fine but I get some test errors. Please take a look.

**Comment by rsutphin** [comment]
While it's true that the change notifier fires for local changes, it doesn't actually call `reload`. At the point that the change watcher is called, the ember-data record is still dirty. The change watcher doesn't reload dirty records to avoid losing local changes. 

So, there's no point in adding a separate rev check. Apologies, I should have looked into this more thoroughly before opening this ticket.
