### ISSUE TITLE
Authentication implementation

### ISSUE THREAD

**Issue by hamzahio** [nolanlawson/ember-pouch#85]
Good day all,

i try to implement authentication in ember-pouch which login & logout but i keep facing problem.

i know there is library named CouchDB Authentication but don't have any idea how to include in the ember project.

your help is highly appreciated

**Comment by nolanlawson** [comment]
`bower install --save pouchdb-authentication` and then it should be part of your Ember app now. :)

**Comment by broerse** [comment]
;-) @ghamha1n It is on my list to implement this. Perhaps we can try to get it to work with [Torii](https://github.com/simplabs/ember-cli-simple-auth-torii). I am willing to try to help with this. @nolanlawson is there a Torii implementation already?

**Comment by nolanlawson** [comment]
@broerse Nope, pouchdb-authentication is basically just a sugar API on top of CouchDB's authentication system; nothing to do with Torii.

**Comment by broerse** [comment]
@nolanlawson Thanks. As said it is on my list to implement authentication and I think Torii is an interesting way to do things.

**Comment by ghamha1n** [comment]
@nolanlawson thanks for your replay, but i stell facing problem when i call 
```
db.login('batman', 'brucewayne').then(function (batman) {
  console.log("I'm Batman.");
  return db.logout();
});
```

error undefined is not a function

**Comment by nolanlawson** [comment]
@ghamha1n You need to include the script in your html page:

```html
<script src="bower_components/pouchdb-authentication/dist/pouchdb-authentication.js"></script>
```

`bower install` will just download the file to your `bower_components`; you still have to add the `script` tag to your page. Alternatively you can `npm install` and `require` it.

**Comment by broerse** [comment]
I think you must load it in [ember-cli-build.js](https://github.com/broerse/ember-cli-blog/blob/master/ember-cli-build.js) the same as `bower_components/moment/moment.js`

**Comment by srsgores** [comment]
@broerse is close, but not quite right; you need to add the following to your ``ember-cli-build.js``:

```
app.import("bower_components/pouchdb-authentication/dist/pouchdb.authentication.min.js");
```

You don't need ``moment.js`` at all, and even if you did, you would just do ``ember install ember-moment``, anyway.

**Comment by broerse** [comment]
@srsgores I was not suggesting adding moment.js ;-) Thanks for helping out with the correct path. I think you must not load the .min version because ember-cli will handle that.

**Comment by broerse** [comment]
It is still in Beta but https://github.com/martinic/ember-simple-auth-pouch is a good working Authentication implementation. Demo: https://bloggr.exmer.com
