### ISSUE TITLE
Issue with sync

### ISSUE THREAD

**Issue by olivierchatry** [nolanlawson/ember-pouch#94]
It seems that if the sync is not done ( at least the first one, when the DB is replicated ) ember pouch is not able to read the data. 
Might be a bug with pouch-relational as I guess you need to hook inside some events for it to works.

**Comment by rsutphin** [comment]
Can you elaborate? Ember-pouch can work without syncing at all. But if you are relying on replication then you will need to replicate before it can read anything. I'm not sure what you're expecting to have happen.

**Comment by olivierchatry** [comment]
Well, I'm doing the usual :
```javascript
            let remote = new PouchDB(config.APP.COUCHDB_HOST + '/' + dbName, {skipSetup: true})
            remote.login(user.get('name'), user.get('dbPassword')).then(
              (user) => {
                let db = new PouchDB(dbName)
                let sync = db.sync(remote, {live:true, retry:true})
              }
            )
```

If I access the model as soon as the db is set ( and not present in the local store ), then nothing is returned from my query.

If it is normal behavior, then I will find a way around it and we can close the task.

**Comment by rsutphin** [comment]
Ember-pouch is only seeing the local db at the time that you do the query. So if the data you query for hasn't replicated in yet, ember-pouch will not see it.

It might be nice if there was some sort of transparent query mode for PouchDB where it queried a remote database as a fallback if data wasn't present locally, but if there is I am not aware of it. If there were, I think that would be a PouchDB feature, not an ember-pouch feature.

**Comment by olivierchatry** [comment]
That make sense, closing the issue

**Comment by dehuszar** [comment]
Is there a non-transparent way to handle this?  All the docs for Ember-Pouch seem to point to syncing and querying data from the local pouch, assuming that all important data starts on my local.  But if the local pouch doesn't contain your data nothing happens.  The only documented way around this is to sync **everything**, which has some prohibitive effects.

What I think would be a useful addition to the docs (and I would be happy to create a PR for said docs if I can get unstuck on how to do this) is an example of an idomatic "Ember way" to query Pouch first for data, and then lazily query CouchDB to see if it contains any un-replicated data without having to do a complete sync.
