### ISSUE TITLE
Switch between CouchDB and PouchDB at runtime?

### ISSUE THREAD

**Issue by cquillen2003** [nolanlawson/ember-pouch#98]
Is switching between CouchDB and PouchDB at runtime possible with this adapter?  I'd like to prompt the user and get permission before pulling their data into the browser.

If not, I might try to create another community CouchDB and/or PouchDB adapter, so any basic advice on how to structure this would be greatly appreciated: one adapter or two and which adapter/serializer to start with (extend)?

**Comment by rsutphin** [comment]
PR #89 has a patch which enables switching between PouchDB instances within the adapter. This would allow switching from a local database to a remote one (i.e., one pointing at a CouchDB database). It hasn't been merged yet, but you could look at it and see if it does what you need. Feedback would be appreciated.

**Comment by cquillen2003** [comment]
Just read through PR #89.  I think this will work.  Thanks!
