### ISSUE TITLE
Question about document _id's

### ISSUE THREAD

**Issue by cquillen2003** [nolanlawson/ember-pouch#99]
Sorry for additional questions, but I am a little confused after reading the docs for both ember-pouch and relational-pouch.

With ember-pouch, are the document id's automatically set to "pokemon_1" or "trainer_2" as mentioned in the README for relational-pouch?

Also, does ember-pouch include the relational-pouch plugin and call the appropriate db.setSchema() methods automatically?

**Comment by rsutphin** [comment]
Document IDs in ember-pouch are determined by relational-pouch, yes. The examples you found in the README are intended to be conceptual. The actual document ID structure also contains a flag that indicates the type of the ID (string, integer, etc.). The section of the README about [parseDocID][] has a concrete example of the actual structure.

[parseDocID]: https://github.com/nolanlawson/relational-pouch#dbrelparsedociddocid

You don't need to do anything with `setSchema` yourself. You can _use_ ember-pouch for the basics without being aware of relational-pouch at all. (Awareness of the document ID structure becomes important when you get into syncing or building indexes, though.)
